services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/crates
      REDIS_URL: redis://redis:6379
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_LOG_LEVEL: "debug"
      ROCKET_DATABASES: '{postgres={url="postgres://postgres:postgres@postgres/crates"}}'

  
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crates
    ports:
      - "5434:5432"
    
  redis:
    image: redis:7.4
    ports:
      - "6380:6379"